POST  https://hayabusa.proxy.rlwy.net:21675/graphql
Content-Type: application/json
X-ACTOR: [1]

{
  "query": "query GetBeverages($filter: BeverageFilterInput, $cursor: ID, $limit: Int) { beverages(filter: $filter, cursor: $cursor, limit: $limit) { items { id name status typeId schemaEditionIds attributes producers { id auid role } origin { latitude longitude } createdAt } } }",
  "variables": {
    "filter": null,
    "limit": 100
  }
}