'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
// Relative import targeting the local type matrix generated by codegen
import { CommissionReplicaType } from '../../../src/gql/graphql';
import { createCompetitionInfrastructure } from './actions';
import { AppHeader } from '@/components/AppHeader';

interface ReplicaState {
    id: string;
    name: string;
    type: CommissionReplicaType;
}

interface CommissionState {
    id: string;
    name: string;
    wineJumperMiniGameEnabled: boolean;
    voiceCommentsEnabled: boolean;
    propertyCommentsEnabled: boolean;
    beverageOriginDuringEvaluationEnabled: boolean;
    plannedStartDate: string;
    plannedEndDate: string;
    replicas: ReplicaState[];
}

interface CompetitionFormState {
    name: string;
    seriesId: string;
    plannedStartDate: string;
    plannedEndDate: string;
    holders: number[][];
    commissions: CommissionState[];
}

interface SeriesOption {
    id: string;
    name: string;
}

export default function CreateCompetitionPage() {
    const router = useRouter();
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [submitError, setSubmitError] = useState<string | null>(null);
    const [seriesList, setSeriesList] = useState<SeriesOption[]>([]);

    const [formData, setFormData] = useState<CompetitionFormState>({
        name: '',
        seriesId: '',
        plannedStartDate: '',
        plannedEndDate: '',
        holders: [[1, 2, 3]],
        commissions: []
    });

    useEffect(() => {
        fetch('http://hayabusa.proxy.rlwy.net:21675/graphql', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                query: '{ competitionSeriesList(limit: 100) { items { id name } } }'
            })
        })
            .then(r => r.json())
            .then(data => {
                const items = data?.data?.competitionSeriesList?.items;
                if (Array.isArray(items)) setSeriesList(items);
            })
            .catch(() => {});
    }, []);

    const handleCompetitionChange = (field: keyof CompetitionFormState, value: any) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    const addCommission = () => {
        const newCommission: CommissionState = {
            id: crypto.randomUUID(),
            name: `Commission ${formData.commissions.length + 1}`,
            wineJumperMiniGameEnabled: false,
            voiceCommentsEnabled: false,
            propertyCommentsEnabled: true,
            beverageOriginDuringEvaluationEnabled: false,
            plannedStartDate: formData.plannedStartDate,
            plannedEndDate: formData.plannedEndDate,
            replicas: []
        };
        setFormData(prev => ({ ...prev, commissions: [...prev.commissions, newCommission] }));
    };

    const removeCommission = (commissionId: string) => {
        setFormData(prev => ({ ...prev, commissions: prev.commissions.filter(c => c.id !== commissionId) }));
    };

    const updateCommission = (commissionId: string, field: keyof CommissionState, value: any) => {
        setFormData(prev => ({
            ...prev,
            commissions: prev.commissions.map(c => c.id === commissionId ? { ...c, [field]: value } : c)
        }));
    };

    const addReplica = (commissionId: string) => {
        setFormData(prev => ({
            ...prev,
            commissions: prev.commissions.map(c => {
                if (c.id !== commissionId) return c;
                const newReplica: ReplicaState = {
                    id: crypto.randomUUID(),
                    name: `Replica ${c.replicas.length + 1}`,
                    type: 'STANDARD'
                };
                return { ...c, replicas: [...c.replicas, newReplica] };
            })
        }));
    };

    const removeReplica = (commissionId: string, replicaId: string) => {
        setFormData(prev => ({
            ...prev,
            commissions: prev.commissions.map(c => {
                if (c.id !== commissionId) return c;
                return { ...c, replicas: c.replicas.filter(r => r.id !== replicaId) };
            })
        }));
    };

    const updateReplica = (commissionId: string, replicaId: string, field: keyof ReplicaState, value: any) => {
        setFormData(prev => ({
            ...prev,
            commissions: prev.commissions.map(c => {
                if (c.id !== commissionId) return c;
                return { ...c, replicas: c.replicas.map(r => r.id === replicaId ? { ...r, [field]: value } : r) };
            })
        }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);
        setSubmitError(null);

        try {
            // Dispatches the full state payload to the Next.js Node.js layer
            const result = await createCompetitionInfrastructure(formData);

            if (!result.success) {
                throw new Error(result.error);
            }

            router.push('/dashboard');
        } catch (err: any) {
            console.error('Cascade activation failed:', err);
            
            const errorMsg = err.message || '';
            const lower = errorMsg.toLowerCase();
            let friendlyMessage = 'An unexpected error occurred while creating the competition. Please try again.';
            
            if (lower.includes('failed to fetch') || lower.includes('fetch failed') || lower.includes('server responded with status')) {
                friendlyMessage = 'Network error: Unable to connect to the server. Please check your internet connection.';
            } else if (lower.includes('seriesid') || lower.includes('series id') || lower.includes('failed to convert argument value')) {
                friendlyMessage = 'Please select a valid Competition Series from the list.';
            } else if (lower.includes('name') && (lower.includes('null') || lower.includes('empty') || lower.includes('required'))) {
                friendlyMessage = 'Please fill in the competition name.';
            } else if (lower.includes('holders')) {
                friendlyMessage = 'Please specify at least one holder for the competition.';
            } else if (lower.includes('failed to initialize competition root node')) {
                friendlyMessage = 'Failed to create the competition. Please review the submitted details.';
            } else if (errorMsg) {
                friendlyMessage = `Error: ${errorMsg}`;
            }
            
            setSubmitError(friendlyMessage);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#F8FAFC] text-[#1E293B] font-sans antialiased">
            <AppHeader activeTab="competitions" />


            <main className="max-w-7xl mx-auto px-12 py-8">
                {submitError && (
                    <div className="mb-6 p-4 bg-red-50 border border-red-200 text-red-600 rounded-2xl text-sm font-medium">
                        ⚠️ {submitError}
                    </div>
                )}

                <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">

                    {/* LEFT COLUMN: Sidebar Details */}
                    <div className="lg:col-span-4 space-y-6">
                        <div className="bg-white p-6 rounded-3xl border border-[#F1F5F9] shadow-[0_8px_30px_rgb(0,0,0,0.02)] space-y-4">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 bg-[#EEF2FF] text-[#5046E5] rounded-2xl flex items-center justify-center font-bold">🏆</div>
                                <div className="flex-1">
                                    <h2 className="text-xs font-bold uppercase tracking-wider text-[#94A3B8]">Competition Series</h2>
                                    <select
                                        className="text-base font-semibold text-[#0F172A] bg-transparent border-b border-transparent hover:border-[#E2E8F0] focus:border-[#5046E5] focus:outline-none w-full mt-0.5 pt-0.5 cursor-pointer"
                                        value={formData.seriesId}
                                        onChange={e => handleCompetitionChange('seriesId', e.target.value)}
                                        disabled={isSubmitting}
                                    >
                                        <option value="">— Select a series —</option>
                                        {seriesList.map(s => (
                                            <option key={s.id} value={s.id}>{s.name}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white p-6 rounded-3xl border border-[#F1F5F9] shadow-[0_8px_30px_rgb(0,0,0,0.02)] space-y-5">
                            <div className="flex items-center gap-2 text-[#5046E5] font-semibold text-sm">
                                <span>📅</span> Schedule Details
                            </div>
                            <div className="space-y-4">
                                <div className="relative pl-4 border-l-2 border-[#E2E8F0] focus-within:border-[#5046E5] transition-colors">
                                    <label className="block text-[10px] font-bold uppercase tracking-wider text-[#94A3B8]">Planned Start</label>
                                    <input
                                        type="datetime-local"
                                        className="w-full text-xs font-medium text-[#334155] bg-transparent border-none outline-none mt-1"
                                        value={formData.plannedStartDate}
                                        onChange={e => handleCompetitionChange('plannedStartDate', e.target.value)}
                                        disabled={isSubmitting}
                                    />
                                </div>
                                <div className="relative pl-4 border-l-2 border-[#E2E8F0] focus-within:border-[#5046E5] transition-colors">
                                    <label className="block text-[10px] font-bold uppercase tracking-wider text-[#94A3B8]">Planned Completion</label>
                                    <input
                                        type="datetime-local"
                                        className="w-full text-xs font-medium text-[#334155] bg-transparent border-none outline-none mt-1"
                                        value={formData.plannedEndDate}
                                        onChange={e => handleCompetitionChange('plannedEndDate', e.target.value)}
                                        disabled={isSubmitting}
                                    />
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* RIGHT COLUMN: Main Panel */}
                    <div className="lg:col-span-8 space-y-6">
                        <div className="bg-white p-8 rounded-3xl border border-[#F1F5F9] shadow-[0_8px_30px_rgb(0,0,0,0.02)] space-y-4">
                            <div className="flex items-start gap-4">
                                <div className="w-14 h-14 bg-[#EEF2FF] text-[#5046E5] rounded-2xl flex items-center justify-center text-xl shadow-sm">🍷</div>
                                <div className="flex-1">
                                    <span className="text-xs font-bold uppercase tracking-wider text-[#94A3B8]">Competition Dashboard</span>
                                    <input
                                        type="text"
                                        required
                                        placeholder="e.g., Wines of the Silver Land 2026"
                                        className="text-2xl font-bold text-[#0F172A] bg-transparent border-b border-transparent hover:border-[#E2E8F0] focus:border-[#5046E5] focus:outline-none w-full mt-1"
                                        value={formData.name}
                                        onChange={e => handleCompetitionChange('name', e.target.value)}
                                        disabled={isSubmitting}
                                    />
                                </div>
                            </div>
                        </div>

                        <div className="bg-white p-8 rounded-3xl border border-[#F1F5F9] shadow-[0_8px_30px_rgb(0,0,0,0.02)] space-y-6">
                            <div className="flex justify-between items-center">
                                <div className="space-y-0.5">
                                    <h3 className="text-lg font-bold text-[#0F172A] flex items-center gap-2"><span>👥</span> Commissions</h3>
                                    <p className="text-xs text-[#94A3B8]">Commissions assigned to this setup</p>
                                </div>
                                <button
                                    type="button"
                                    onClick={addCommission}
                                    disabled={isSubmitting}
                                    className="bg-[#5046E5] text-white text-xs font-semibold px-4 py-2 rounded-xl hover:bg-[#4338CA] transition-colors shadow-sm disabled:opacity-50"
                                >
                                    + Add Commission
                                </button>
                            </div>

                            {formData.commissions.length === 0 ? (
                                <div className="text-center py-12 bg-[#F8FAFC] rounded-2xl border border-dashed border-[#E2E8F0] text-sm text-[#94A3B8]">
                                    No commissions configuration found. Click the button above to add a dynamic node.
                                </div>
                            ) : (
                                <div className="space-y-4">
                                    {formData.commissions.map((commission) => (
                                        <div key={commission.id} className="p-5 bg-[#F8FAFC] border border-[#F1F5F9] rounded-2xl space-y-4">
                                            <div className="flex justify-between items-center pb-3 border-b border-[#E2E8F0]">
                                                <div className="flex items-center gap-3 flex-1 max-w-md">
                                                    <div className="w-8 h-8 bg-white text-[#5046E5] border border-[#E2E8F0] rounded-xl flex items-center justify-center text-sm shadow-sm">🔮</div>
                                                    <input
                                                        type="text"
                                                        className="font-bold text-[#1E293B] text-sm bg-transparent border-b border-transparent hover:border-[#CBD5E1] focus:border-[#5046E5] focus:outline-none w-full py-0.5"
                                                        value={commission.name}
                                                        onChange={e => updateCommission(commission.id, 'name', e.target.value)}
                                                        disabled={isSubmitting}
                                                    />
                                                </div>
                                                <button
                                                    type="button"
                                                    onClick={() => removeCommission(commission.id)}
                                                    disabled={isSubmitting}
                                                    className="text-xs font-semibold text-red-500 hover:text-red-700 disabled:opacity-50"
                                                >
                                                    Remove
                                                </button>
                                            </div>

                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-medium text-[#475569]">
                                                <label className="flex items-center gap-2.5 bg-white p-3 rounded-xl border border-[#E2E8F0] cursor-pointer">
                                                    <input
                                                        type="checkbox"
                                                        className="w-4 h-4 text-[#5046E5] focus:ring-[#5046E5] accent-[#5046E5]"
                                                        checked={commission.wineJumperMiniGameEnabled}
                                                        onChange={e => updateCommission(commission.id, 'wineJumperMiniGameEnabled', e.target.checked)}
                                                        disabled={isSubmitting}
                                                    />
                                                    <span>WineJumper Mini-game Interaction</span>
                                                </label>
                                                <label className="flex items-center gap-2.5 bg-white p-3 rounded-xl border border-[#E2E8F0] cursor-pointer">
                                                    <input
                                                        type="checkbox"
                                                        className="w-4 h-4 text-[#5046E5] focus:ring-[#5046E5] accent-[#5046E5]"
                                                        checked={commission.voiceCommentsEnabled}
                                                        onChange={e => updateCommission(commission.id, 'voiceCommentsEnabled', e.target.checked)}
                                                        disabled={isSubmitting}
                                                    />
                                                    <span>Allow Voice Stream Notes</span>
                                                </label>
                                                <label className="flex items-center gap-2.5 bg-white p-3 rounded-xl border border-[#E2E8F0] cursor-pointer">
                                                    <input
                                                        type="checkbox"
                                                        className="w-4 h-4 text-[#5046E5] focus:ring-[#5046E5] accent-[#5046E5]"
                                                        checked={commission.propertyCommentsEnabled}
                                                        onChange={e => updateCommission(commission.id, 'propertyCommentsEnabled', e.target.checked)}
                                                        disabled={isSubmitting}
                                                    />
                                                    <span>Structural Property Annotation</span>
                                                </label>
                                                <label className="flex items-center gap-2.5 bg-white p-3 rounded-xl border border-[#E2E8F0] cursor-pointer">
                                                    <input
                                                        type="checkbox"
                                                        className="w-4 h-4 text-[#5046E5] focus:ring-[#5046E5] accent-[#5046E5]"
                                                        checked={commission.beverageOriginDuringEvaluationEnabled}
                                                        onChange={e => updateCommission(commission.id, 'beverageOriginDuringEvaluationEnabled', e.target.checked)}
                                                        disabled={isSubmitting}
                                                    />
                                                    <span>Expose Beverage Origin Metadata</span>
                                                </label>
                                            </div>

                                            <div className="pt-2 space-y-3">
                                                <div className="flex justify-between items-center">
                                                    <span className="text-xs font-bold uppercase tracking-wider text-[#94A3B8]">Replicas Structure ({commission.replicas.length})</span>
                                                    <button
                                                        type="button"
                                                        onClick={() => addReplica(commission.id)}
                                                        disabled={isSubmitting}
                                                        className="text-[11px] font-bold text-[#5046E5] bg-[#EEF2FF] px-2.5 py-1 rounded-lg hover:bg-[#E0E7FF] disabled:opacity-50"
                                                    >
                                                        + Add Replica
                                                    </button>
                                                </div>

                                                {commission.replicas.length > 0 && (
                                                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                                                        {commission.replicas.map((replica) => (
                                                            <div key={replica.id} className="flex items-center gap-2 bg-white p-2.5 border border-[#E2E8F0] rounded-xl">
                                                                <div className="flex-1 space-y-1">
                                                                    <input
                                                                        type="text"
                                                                        className="w-full text-xs font-bold text-[#1E293B] bg-transparent border-b border-transparent hover:border-[#E2E8F0] focus:border-[#5046E5] focus:outline-none"
                                                                        value={replica.name}
                                                                        onChange={e => updateReplica(commission.id, replica.id, 'name', e.target.value)}
                                                                        disabled={isSubmitting}
                                                                    />
                                                                    <select
                                                                        className="w-full text-[11px] bg-transparent text-[#64748B] outline-none cursor-pointer"
                                                                        value={replica.type}
                                                                        onChange={e => updateReplica(commission.id, replica.id, 'type', e.target.value as CommissionReplicaType)}
                                                                        disabled={isSubmitting}
                                                                    >
                                                                        <option value="STANDARD">STANDARD</option>
                                                                        <option value="TRAINEE">TRAINEE</option>
                                                                    </select>
                                                                </div>
                                                                <button
                                                                    type="button"
                                                                    onClick={() => removeReplica(commission.id, replica.id)}
                                                                    disabled={isSubmitting}
                                                                    className="text-lg text-[#94A3B8] hover:text-red-500 px-1 disabled:opacity-50"
                                                                >
                                                                    &times;
                                                                </button>
                                                            </div>
                                                        ))}
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>

                    {/* ACTION BAR */}
                    <div className="col-span-12 flex justify-end gap-3 pt-4 border-t border-[#E2E8F0]">
                        <button
                            type="button"
                            onClick={() => router.push('/dashboard')}
                            disabled={isSubmitting}
                            className="px-6 py-2.5 bg-white border border-[#E2E8F0] text-[#475569] text-sm font-semibold rounded-xl hover:bg-[#F8FAFC] disabled:opacity-50"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={isSubmitting}
                            className="px-6 py-2.5 bg-[#5046E5] text-white text-sm font-semibold rounded-xl hover:bg-[#4338CA] transition-all shadow-[0_4px_12px_rgba(80,70,229,0.2)] disabled:opacity-75 flex items-center gap-2"
                        >
                            {isSubmitting ? (
                                <>
                                    <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                    Creating Structure...
                                </>
                            ) : (
                                'Save Structure'
                            )}
                        </button>
                    </div>

                </form>
            </main>
        </div>
    );
}